import Head from 'next/head'
import Image from 'next/image'
import Header from '../Components/header'
import Navbar from '../Components/navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      <Navbar />
    </div>
  )
}
