import React from 'react'
import Head from 'next/head'
import FeatureProduct from '../components/featureProduct'
import Footer from '../components/Footer'
import Hero from '../Components/hero'
import Navbar from '../components/Navbar'
import ProductCaregory from '../Components/ProductCaregory'
import styles from '../styles/Home.module.css'
import Product from './product'
import Test from '../components/test'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <ProductCaregory />
      <FeatureProduct/>
      <Footer />
      {/* <Test/> */}
    </div>
  )
}

